using System.Text.RegularExpressions;
using ClosedXML.Excel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PengirimanApi.Data;
using PengirimanApi.Models;
using PengirimanApi.Services;

namespace PengirimanApi.Controllers;

// Global backup export - one .xlsx with one sheet per main table, for the annual-archive/backup
// use case that the seven modules' own per-filter /export endpoints (ExportController and its
// siblings) don't cover: those export a filtered, formatted view of one module at a time, this
// exports everything, raw, in one file. Super Admin only, unlike the per-module exports (which
// are RequireRoleAsync() - any role - since those are scoped to what the caller can already see).
//
// Columns are generated by reflection instead of hand-listed (contrast ExportController's static
// Columns array) - a raw backup should stay complete as models grow, and hand-maintaining ~20
// column lists across every table here would drift out of sync exactly the way a backup can't
// afford to. Only "simple" scalar properties are included; EF navigation properties and
// collections are automatically skipped since they aren't one of the recognized types.
[Route("api/superadmin")]
public class SuperAdminExportController : ApiControllerBase
{
    private readonly AppDbContext _db;

    public SuperAdminExportController(AppDbContext db, CurrentUserService currentUser) : base(currentUser)
    {
        _db = db;
    }

    [HttpGet("export-all")]
    public async Task<IActionResult> ExportAll()
    {
        var (_, error) = await RequireRoleAsync(RoleEnum.SUPER_ADMIN);
        if (error != null) return error;

        using var wb = new XLWorkbook();

        AddSheet(wb, "Ekspedisi", await _db.Pengiriman.AsNoTracking().OrderBy(x => x.Id).ToListAsync());
        AddSheet(wb, "Ekspedisi - Log Status", await _db.PengirimanLogs.AsNoTracking().OrderBy(x => x.Id).ToListAsync());
        AddSheet(wb, "Ekspedisi - Invoice", await _db.Invoices.AsNoTracking().OrderBy(x => x.Id).ToListAsync());

        AddSheet(wb, "Office Supplies", await _db.PermintaanAtks.AsNoTracking().OrderBy(x => x.Id).ToListAsync());
        AddSheet(wb, "Office Supplies - Log Status", await _db.PermintaanAtkLogs.AsNoTracking().OrderBy(x => x.Id).ToListAsync());
        AddSheet(wb, "Office Supplies - Invoice", await _db.AtkInvoices.AsNoTracking().OrderBy(x => x.Id).ToListAsync());

        AddSheet(wb, "Maintenance", await _db.PerbaikanSaranas.AsNoTracking().OrderBy(x => x.Id).ToListAsync());
        AddSheet(wb, "Maintenance - Log Status", await _db.PerbaikanSaranaLogs.AsNoTracking().OrderBy(x => x.Id).ToListAsync());

        AddSheet(wb, "Arsip", await _db.PermintaanArsips.AsNoTracking().OrderBy(x => x.Id).ToListAsync());
        AddSheet(wb, "Arsip - Log Status", await _db.PermintaanArsipLogs.AsNoTracking().OrderBy(x => x.Id).ToListAsync());

        AddSheet(wb, "Booking Ruang Meeting", await _db.BookingRuangs.AsNoTracking().OrderBy(x => x.Id).ToListAsync());
        AddSheet(wb, "Booking Ruang - Log Status", await _db.BookingRuangLogs.AsNoTracking().OrderBy(x => x.Id).ToListAsync());

        AddSheet(wb, "Booking Kendaraan", await _db.BookingKendaraans.AsNoTracking().OrderBy(x => x.Id).ToListAsync());
        AddSheet(wb, "Booking Kendaraan - Log", await _db.BookingKendaraanLogs.AsNoTracking().OrderBy(x => x.Id).ToListAsync());

        AddSheet(wb, "Users", await _db.Users.AsNoTracking().OrderBy(x => x.Id).ToListAsync(), "PasswordHash");

        AddSheet(wb, "Organisasi - Direktorat", await _db.OrgDirektorats.AsNoTracking().OrderBy(x => x.Id).ToListAsync());
        AddSheet(wb, "Organisasi - Divisi", await _db.OrgDivisis.AsNoTracking().OrderBy(x => x.Id).ToListAsync());
        AddSheet(wb, "Organisasi - Departemen", await _db.OrgDepartemens.AsNoTracking().OrderBy(x => x.Id).ToListAsync());

        AddSheet(wb, "Master Data", await _db.MasterDataItems.AsNoTracking().OrderBy(x => x.Category).ThenBy(x => x.SortOrder).ToListAsync());

        AddSheet(wb, "Pengaturan Aplikasi", await _db.AppSettings.AsNoTracking().ToListAsync());
        AddSheet(wb, "Hari Libur", await _db.Holidays.AsNoTracking().OrderBy(x => x.Date).ToListAsync());

        AddSheet(wb, "Riwayat Penghapusan", await _db.DeletionLogs.AsNoTracking().OrderBy(x => x.Id).ToListAsync());

        using var stream = new MemoryStream();
        wb.SaveAs(stream);
        var filename = $"Backup_GAAS_{DateTime.UtcNow:yyyyMMdd_HHmmss}.xlsx";
        return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", filename);
    }

    private static void AddSheet<T>(XLWorkbook wb, string sheetName, IReadOnlyList<T> rows, params string[] exclude)
    {
        var props = typeof(T).GetProperties()
            .Where(p => p.CanRead && IsExportableProperty(p.PropertyType) && !exclude.Contains(p.Name))
            .ToArray();

        var ws = wb.Worksheets.Add(sheetName.Length > 31 ? sheetName[..31] : sheetName);

        for (var c = 0; c < props.Length; c++)
        {
            var cell = ws.Cell(1, c + 1);
            cell.Value = Humanize(props[c].Name);
            cell.Style.Font.Bold = true;
        }

        for (var r = 0; r < rows.Count; r++)
        {
            for (var c = 0; c < props.Length; c++)
                SetCellValue(ws.Cell(r + 2, c + 1), props[c].GetValue(rows[r]));
        }

        if (props.Length > 0)
        {
            ws.Columns(1, props.Length).AdjustToContents();
            foreach (var col in ws.Columns(1, props.Length))
            {
                if (col.Width > 40) col.Width = 40;
            }
        }
    }

    private static bool IsExportableProperty(Type type)
    {
        var t = Nullable.GetUnderlyingType(type) ?? type;
        return t.IsEnum
            || t == typeof(string) || t == typeof(int) || t == typeof(long) || t == typeof(decimal)
            || t == typeof(double) || t == typeof(float) || t == typeof(bool)
            || t == typeof(DateTime) || t == typeof(DateOnly) || t == typeof(TimeOnly) || t == typeof(Guid);
    }

    private static void SetCellValue(IXLCell cell, object? value)
    {
        switch (value)
        {
            case null: cell.Value = ""; break;
            case bool b: cell.Value = b; break;
            case int i: cell.Value = i; break;
            case long l: cell.Value = l; break;
            case decimal dec: cell.Value = dec; break;
            case double d: cell.Value = d; break;
            case float f: cell.Value = (double)f; break;
            case DateTime dt: cell.Value = dt; break;
            case DateOnly d1: cell.Value = d1.ToString("yyyy-MM-dd"); break;
            case TimeOnly t1: cell.Value = t1.ToString("HH:mm"); break;
            case Guid g: cell.Value = g.ToString(); break;
            case Enum e: cell.Value = e.ToString(); break;
            default: cell.Value = value.ToString() ?? ""; break;
        }
    }

    // "NomorTransmittal" -> "Nomor Transmittal" - generated headers instead of hand-labeled ones,
    // see the class comment for why.
    private static string Humanize(string propName) => Regex.Replace(propName, "(?<!^)([A-Z])", " $1");
}
