--
-- PostgreSQL database dump
--

\restrict yeT29FmHBb1ARYbLUefjvr8ipOYCbs4bj4lHyzTbklqOXRvL9iT46ePvEP6hS2l

-- Dumped from database version 16.13 (Ubuntu 16.13-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.13 (Ubuntu 16.13-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: invoices; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.invoices (
    id integer NOT NULL,
    bulan character varying(7) NOT NULL,
    file_path character varying(500) NOT NULL,
    original_filename character varying(255) NOT NULL,
    status character varying(20) NOT NULL,
    catatan text,
    uploaded_by integer NOT NULL,
    reviewed_by integer,
    uploaded_at timestamp with time zone NOT NULL,
    reviewed_at timestamp with time zone
);


--
-- Name: invoices_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.invoices ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.invoices_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pengiriman; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pengiriman (
    id integer NOT NULL,
    no_resi character varying(100),
    tanggal date NOT NULL,
    tujuan_penerimaan character varying(255) NOT NULL,
    jumlah_item integer NOT NULL,
    nama_pengirim character varying(255) NOT NULL,
    no_telepon_pengirim character varying(50) NOT NULL,
    divisi character varying(255) NOT NULL,
    kode_program character varying(100) NOT NULL,
    nama_penerima character varying(255) NOT NULL,
    alamat_penerima text NOT NULL,
    no_telepon_penerima character varying(50) NOT NULL,
    asuransi_status character varying(20) NOT NULL,
    request_packing character varying(255) NOT NULL,
    catatan text,
    berat_barang_kg numeric(10,2),
    asuransi_harga numeric(14,2),
    sub_total numeric(14,2),
    total numeric(14,2),
    status character varying(50) NOT NULL,
    reject_reason text,
    created_by integer NOT NULL,
    approved_by_user_approval integer,
    approved_by_ga integer,
    approved_by_ga_approval integer,
    approved_by_kpu integer,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    approved_user_approval_at timestamp with time zone,
    approved_ga_at timestamp with time zone,
    approved_ga_approval_at timestamp with time zone,
    approved_kpu_at timestamp with time zone
);


--
-- Name: pengiriman_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.pengiriman ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pengiriman_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pengiriman_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pengiriman_logs (
    id integer NOT NULL,
    pengiriman_id integer NOT NULL,
    action character varying(50) NOT NULL,
    actor_id integer,
    reason text,
    created_at timestamp with time zone NOT NULL
);


--
-- Name: pengiriman_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.pengiriman_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pengiriman_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id integer NOT NULL,
    email character varying(255) NOT NULL,
    password_hash character varying(255) NOT NULL,
    nama character varying(255) NOT NULL,
    role character varying(50) NOT NULL,
    direktorat character varying(255),
    created_at timestamp with time zone NOT NULL
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: invoices; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.invoices (id, bulan, file_path, original_filename, status, catatan, uploaded_by, reviewed_by, uploaded_at, reviewed_at) FROM stdin;
1	2026-07	8b2506bb245141b6a031004b523ab547.pdf	dummy-invoice.pdf	APPROVED	Sudah sesuai, disetujui	17	15	2026-07-28 01:15:56+00	2026-07-28 01:16:00+00
\.


--
-- Data for Name: pengiriman; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.pengiriman (id, no_resi, tanggal, tujuan_penerimaan, jumlah_item, nama_pengirim, no_telepon_pengirim, divisi, kode_program, nama_penerima, alamat_penerima, no_telepon_penerima, asuransi_status, request_packing, catatan, berat_barang_kg, asuransi_harga, sub_total, total, status, reject_reason, created_by, approved_by_user_approval, approved_by_ga, approved_by_ga_approval, approved_by_kpu, created_at, updated_at, approved_user_approval_at, approved_ga_at, approved_ga_approval_at, approved_kpu_at) FROM stdin;
1	\N	2026-07-27	Test 5-Stage Flow	2	Budi	081211110000	Finance	1103-018206-290313-4709	Andi	Jl. Merdeka No 1	081234567890	Tidak	Tidak	\N	\N	\N	\N	\N	APPROVED_GA_APPROVAL	\N	1	8	15	16	\N	2026-07-27 06:33:16+00	2026-07-27 06:33:24+00	2026-07-27 06:33:20+00	2026-07-27 06:33:22+00	2026-07-27 06:33:25+00	\N
2	AWB999888	2026-07-27	Test 5-Stage Flow	2	Budi	081211110000	Finance	1103-018206-290313-4709	Andi	Jl. Merdeka No 1	081234567890	Tidak	Tidak	\N	2.50	0.00	50000.00	50000.00	COMPLETED	\N	1	8	15	16	17	2026-07-27 06:34:12+00	2026-07-27 06:34:22+00	2026-07-27 06:34:16+00	2026-07-27 06:34:18+00	2026-07-27 06:34:20+00	2026-07-27 06:34:22+00
3	\N	2026-07-27	Test Reject Flow	1	Budi	081211110000	Finance	1103-018206-290313-4709	Andi	Jl. Merdeka No 1	081234567890	Tidak	Tidak	\N	\N	\N	\N	\N	REJECTED_GA	Barang fisik tidak sesuai	1	8	\N	\N	\N	2026-07-27 06:34:56+00	2026-07-27 06:35:07+00	2026-07-27 06:35:05+00	\N	\N	\N
5	\N	2026-07-29	Test Approval Log Timeline	2	Budi	081211110000	Finance	1103-018206-290313-4709	Andi	Jl. Test No 1	081234567899	Tidak	Tidak	\N	\N	\N	\N	\N	APPROVED_GA	\N	1	8	15	\N	\N	2026-07-29 03:02:49+00	2026-07-29 03:02:51+00	2026-07-29 03:02:51+00	2026-07-29 03:02:51+00	\N	\N
\.


--
-- Data for Name: pengiriman_logs; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.pengiriman_logs (id, pengiriman_id, action, actor_id, reason, created_at) FROM stdin;
1	5	CREATED	1	\N	2026-07-29 03:02:49+00
2	5	SUBMITTED	1	\N	2026-07-29 03:02:49+00
3	5	REJECTED_USER_APPROVAL	8	Nomor telepon penerima salah	2026-07-29 03:02:50+00
4	5	REVISED	1	\N	2026-07-29 03:02:50+00
5	5	SUBMITTED	1	\N	2026-07-29 03:02:50+00
6	5	APPROVED_USER_APPROVAL	8	\N	2026-07-29 03:02:50+00
7	5	APPROVED_GA	15	\N	2026-07-29 03:02:51+00
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.users (id, email, password_hash, nama, role, direktorat, created_at) FROM stdin;
1	keuanganbisnis.au@gmail.com	$2b$12$VIb9maepnp741CbGTh34Se6A1Gmj3ZccDChtnNPGcZUWbkRJB9tES	Direktorat Keuangan dan Dukungan Bisnis	ADMIN_USER	Direktorat Keuangan dan Dukungan Bisnis	2026-07-27 06:32:41+00
2	operasi.au@gmail.com	$2b$12$eLS0yKDPxNQL/mR/BLL2A.sEfNAcu7MAi1mgZWhI3/6CGqlVGOiWO	Direktorat Operasi	ADMIN_USER	Direktorat Operasi	2026-07-27 06:32:41+00
3	teknikdanpengembangan.au@gmail.com	$2b$12$TL.l/tCrk0lL2ZO2prKuhOfuJHaabwE0WnZtY8BALwEYs48FrjYYm	Direktorat Teknik dan Pengembangan	ADMIN_USER	Direktorat Teknik dan Pengembangan	2026-07-27 06:32:41+00
4	corporatesecretary.au@gmail.com	$2b$12$FywICaFAMlVUkLpcM5XX9OUKuK92nq93z2UelIYCbYptrtB9qIqxK	Corporate Secretary	ADMIN_USER	Corporate Secretary	2026-07-27 06:32:41+00
5	chiefauditexecutive.au@gmail.com	$2b$12$4LvESp0pPLihs7oi/zOknej1NwV8PIm/bCxDLIM3Opg6HOlFEA07.	Chief Audit Executive	ADMIN_USER	Chief Audit Executive	2026-07-27 06:32:41+00
6	qhsse.au@gmail.com	$2b$12$bWuMrRCglFDGV2kyN3T3sO9KQpAaYHYht/Ryqiwrc5lRdXUHPfnKG	QH SSE	ADMIN_USER	QH SSE	2026-07-27 06:32:41+00
7	strategicplanning.au@gmail.com	$2b$12$94w3jmUJrbG2kwfyFrMwSewXp019LY7odILWRdxWL41h3H30jG43C	Strategic Planning	ADMIN_USER	Strategic Planning	2026-07-27 06:32:41+00
8	keuanganbisnis.approval@gmail.com	$2b$12$xO5hsTC/RBZ9vsnA2AOL0.hKURD25r2m5ouMPCSUfrVYeqg.S2ao6	Direktorat Keuangan dan Dukungan Bisnis (Approval)	USER_APPROVAL	Direktorat Keuangan dan Dukungan Bisnis	2026-07-27 06:32:41+00
9	operasi.approval@gmail.com	$2b$12$dYg012wfFW8KqiLq4tepHO0tRe6SdvhFJ2Rr8HK9UlbUvel4wlZdW	Direktorat Operasi (Approval)	USER_APPROVAL	Direktorat Operasi	2026-07-27 06:32:41+00
10	teknikdanpengembangan.approval@gmail.com	$2b$12$ES4dEeCWHIn8WZTgpa7HQeCZ41nfWpRJhD5rJ53SJZ4PEVfsyX/eu	Direktorat Teknik dan Pengembangan (Approval)	USER_APPROVAL	Direktorat Teknik dan Pengembangan	2026-07-27 06:32:41+00
11	corporatesecretary.approval@gmail.com	$2b$12$SWXPrpYTwE5UAUhfgYVCROBXIaLWRcRD6QsAffxPHPvHJ62RRqxuW	Corporate Secretary (Approval)	USER_APPROVAL	Corporate Secretary	2026-07-27 06:32:41+00
12	chiefauditexecutive.approval@gmail.com	$2b$12$PhPqbRPgP3ZfLsgqgnkCbe/vH9GBXhbrqMOLx2YsbLmVD8ks5fczW	Chief Audit Executive (Approval)	USER_APPROVAL	Chief Audit Executive	2026-07-27 06:32:41+00
13	qhsse.approval@gmail.com	$2b$12$qWg2N2BmnXHv4Cl9OywvX.RNFmT8qfOQC7lOyNGT160rFmAy5qFIm	QH SSE (Approval)	USER_APPROVAL	QH SSE	2026-07-27 06:32:41+00
14	strategicplanning.approval@gmail.com	$2b$12$dHnnUK9cdE0R0TH3gEMpYexRZ7R43.qx55jtcsf5r/ZqNzruQvdWO	Strategic Planning (Approval)	USER_APPROVAL	Strategic Planning	2026-07-27 06:32:41+00
15	admingeneralaffair.aga@gmail.com	$2b$12$PXV5bYDnNdaFYfTka6E4BuFVBpJ2omTGERMCPBRTxtXHCnLwRLdLy	Admin General Affair	ADMIN_GA	\N	2026-07-27 06:32:41+00
16	generalaffairapproval.aga@gmail.com	$2b$12$toswRcSHBMYWDAYrq8nlAOYtm0nK/PKzYpahgU3rHIy3wVPciz9r.	General Affair Approval	GA_APPROVAL	\N	2026-07-27 06:32:41+00
17	kpu.kpu@gmail.com	$2b$12$xh0k7tyWongH0E8YqBQtOej.5AYlMnKsAj5qSXCgKw53jC6PRKnDq	KPU	KPU	\N	2026-07-27 06:32:41+00
18	superadmin.admin@gmail.com	$2b$12$htBglfGE6imV0SEmjVQWKeOANu8ekA0OPk.044.bAKAxelprkeYlu	Super Admin	SUPER_ADMIN	\N	2026-08-04 02:18:26+00
\.


--
-- Name: invoices_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.invoices_id_seq', 1, true);


--
-- Name: pengiriman_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.pengiriman_id_seq', 5, true);


--
-- Name: pengiriman_logs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.pengiriman_logs_id_seq', 9, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.users_id_seq', 18, true);


--
-- Name: invoices PK_invoices; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invoices
    ADD CONSTRAINT "PK_invoices" PRIMARY KEY (id);


--
-- Name: pengiriman PK_pengiriman; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pengiriman
    ADD CONSTRAINT "PK_pengiriman" PRIMARY KEY (id);


--
-- Name: pengiriman_logs PK_pengiriman_logs; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pengiriman_logs
    ADD CONSTRAINT "PK_pengiriman_logs" PRIMARY KEY (id);


--
-- Name: users PK_users; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT "PK_users" PRIMARY KEY (id);


--
-- Name: IX_invoices_reviewed_by; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_invoices_reviewed_by" ON public.invoices USING btree (reviewed_by);


--
-- Name: IX_invoices_uploaded_by; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_invoices_uploaded_by" ON public.invoices USING btree (uploaded_by);


--
-- Name: IX_pengiriman_created_by; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_pengiriman_created_by" ON public.pengiriman USING btree (created_by);


--
-- Name: IX_pengiriman_logs_actor_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_pengiriman_logs_actor_id" ON public.pengiriman_logs USING btree (actor_id);


--
-- Name: IX_pengiriman_logs_pengiriman_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_pengiriman_logs_pengiriman_id" ON public.pengiriman_logs USING btree (pengiriman_id);


--
-- Name: IX_users_email; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_users_email" ON public.users USING btree (email);


--
-- Name: invoices FK_invoices_users_reviewed_by; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invoices
    ADD CONSTRAINT "FK_invoices_users_reviewed_by" FOREIGN KEY (reviewed_by) REFERENCES public.users(id) ON DELETE RESTRICT;


--
-- Name: invoices FK_invoices_users_uploaded_by; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invoices
    ADD CONSTRAINT "FK_invoices_users_uploaded_by" FOREIGN KEY (uploaded_by) REFERENCES public.users(id) ON DELETE RESTRICT;


--
-- Name: pengiriman_logs FK_pengiriman_logs_pengiriman_pengiriman_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pengiriman_logs
    ADD CONSTRAINT "FK_pengiriman_logs_pengiriman_pengiriman_id" FOREIGN KEY (pengiriman_id) REFERENCES public.pengiriman(id) ON DELETE CASCADE;


--
-- Name: pengiriman_logs FK_pengiriman_logs_users_actor_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pengiriman_logs
    ADD CONSTRAINT "FK_pengiriman_logs_users_actor_id" FOREIGN KEY (actor_id) REFERENCES public.users(id) ON DELETE RESTRICT;


--
-- Name: pengiriman FK_pengiriman_users_created_by; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pengiriman
    ADD CONSTRAINT "FK_pengiriman_users_created_by" FOREIGN KEY (created_by) REFERENCES public.users(id) ON DELETE RESTRICT;


--
-- PostgreSQL database dump complete
--

\unrestrict yeT29FmHBb1ARYbLUefjvr8ipOYCbs4bj4lHyzTbklqOXRvL9iT46ePvEP6hS2l

