// Starter catalog of common office-supply items for Office Supplies (Permintaan ATK) - there is
// no real product database yet, so this seeds the "Nama Barang" autocomplete (see
// AtkFormModal/AtkDetailModal's `list={ATK_CATALOG_DATALIST_ID}`) with 200 realistic items and a
// sensible default Satuan. It only suggests - the field stays free text, so anything not listed
// here can still be typed in by hand.
export interface AtkCatalogItem {
  namaBarang: string;
  satuan: string;
}

export const ATK_CATALOG_DATALIST_ID = "atk-catalog-nama-barang";

export const ATK_CATALOG: AtkCatalogItem[] = [
  // Alat Tulis
  { namaBarang: "Pulpen Standard Hitam", satuan: "pcs" },
  { namaBarang: "Pulpen Standard Biru", satuan: "pcs" },
  { namaBarang: "Pulpen Standard Merah", satuan: "pcs" },
  { namaBarang: "Pulpen Gel Hitam", satuan: "pcs" },
  { namaBarang: "Pulpen Gel Biru", satuan: "pcs" },
  { namaBarang: "Pensil 2B", satuan: "pcs" },
  { namaBarang: "Pensil Mekanik 0.5mm", satuan: "pcs" },
  { namaBarang: "Isi Pensil Mekanik 0.5mm", satuan: "pack" },
  { namaBarang: "Penghapus Pensil", satuan: "pcs" },
  { namaBarang: "Penggaris Plastik 30cm", satuan: "pcs" },
  { namaBarang: "Penggaris Besi 60cm", satuan: "pcs" },
  { namaBarang: "Spidol Permanent Hitam", satuan: "pcs" },
  { namaBarang: "Spidol Permanent Biru", satuan: "pcs" },
  { namaBarang: "Spidol Whiteboard Hitam", satuan: "pcs" },
  { namaBarang: "Spidol Whiteboard Merah", satuan: "pcs" },
  { namaBarang: "Spidol Whiteboard Biru", satuan: "pcs" },
  { namaBarang: "Tinta Isi Ulang Spidol Whiteboard", satuan: "botol" },
  { namaBarang: "Highlighter Kuning", satuan: "pcs" },
  { namaBarang: "Highlighter Hijau", satuan: "pcs" },
  { namaBarang: "Highlighter Pink", satuan: "pcs" },
  { namaBarang: "Correction Tape (Tip-Ex Kertas)", satuan: "pcs" },
  { namaBarang: "Correction Pen (Tip-Ex Cair)", satuan: "pcs" },
  { namaBarang: "Lem Stick", satuan: "pcs" },
  { namaBarang: "Lem Kertas Cair", satuan: "botol" },
  { namaBarang: "Isolasi Bening 1 Inch", satuan: "roll" },
  { namaBarang: "Isolasi Bening 2 Inch", satuan: "roll" },
  { namaBarang: "Double Tape", satuan: "roll" },
  { namaBarang: "Lakban Coklat", satuan: "roll" },
  { namaBarang: "Lakban Hitam", satuan: "roll" },
  { namaBarang: "Cutter Kecil", satuan: "pcs" },
  { namaBarang: "Cutter Besar", satuan: "pcs" },
  { namaBarang: "Gunting Kantor", satuan: "pcs" },
  { namaBarang: "Rautan Pensil", satuan: "pcs" },
  { namaBarang: "Stabilo Boss Set 4 Warna", satuan: "box" },
  { namaBarang: "Pensil Warna Set 12 Warna", satuan: "box" },

  // Kertas & Cetak
  { namaBarang: "Kertas HVS A4 70gsm", satuan: "rim" },
  { namaBarang: "Kertas HVS A4 80gsm", satuan: "rim" },
  { namaBarang: "Kertas HVS F4 70gsm", satuan: "rim" },
  { namaBarang: "Kertas HVS F4 80gsm", satuan: "rim" },
  { namaBarang: "Kertas HVS A3 80gsm", satuan: "rim" },
  { namaBarang: "Kertas Concord/NCR 3 Ply", satuan: "rim" },
  { namaBarang: "Kertas Foto Glossy A4", satuan: "pack" },
  { namaBarang: "Kertas Karton Manila", satuan: "lembar" },
  { namaBarang: "Kertas Buffalo Warna", satuan: "lembar" },
  { namaBarang: "Sticky Notes 3x3 Inch", satuan: "pack" },
  { namaBarang: "Sticky Notes Kecil", satuan: "pack" },
  { namaBarang: "Sticky Notes Flag/Index", satuan: "pack" },
  { namaBarang: "Amplop Coklat Kecil", satuan: "pack" },
  { namaBarang: "Amplop Coklat Besar", satuan: "pack" },
  { namaBarang: "Amplop Putih Polos", satuan: "pack" },
  { namaBarang: "Amplop Kop Perusahaan", satuan: "box" },
  { namaBarang: "Kertas Fax Roll", satuan: "roll" },
  { namaBarang: "Kertas Thermal Kasir", satuan: "roll" },
  { namaBarang: "Buku Tulis Folio 100 Lembar", satuan: "pcs" },
  { namaBarang: "Buku Agenda Kerja", satuan: "pcs" },
  { namaBarang: "Buku Kwitansi", satuan: "pcs" },
  { namaBarang: "Kalender Meja", satuan: "pcs" },
  { namaBarang: "Post It Cube", satuan: "pcs" },
  { namaBarang: "Kertas Label Nama", satuan: "pack" },
  { namaBarang: "Kertas Label Barcode", satuan: "roll" },
  { namaBarang: "Continuous Form 1 Ply", satuan: "box" },
  { namaBarang: "Continuous Form 2 Ply", satuan: "box" },
  { namaBarang: "Kertas Minute Pad", satuan: "pcs" },
  { namaBarang: "Kertas Origami Warna", satuan: "pack" },
  { namaBarang: "Plastik Laminating A4", satuan: "pack" },

  // Perlengkapan Meja / Kantor
  { namaBarang: "Stapler Kecil", satuan: "pcs" },
  { namaBarang: "Stapler Besar (Heavy Duty)", satuan: "pcs" },
  { namaBarang: "Isi Staples No 10", satuan: "box" },
  { namaBarang: "Isi Staples No 3", satuan: "box" },
  { namaBarang: "Perforator/Pelubang Kertas 2 Lubang", satuan: "pcs" },
  { namaBarang: "Perforator Besar 4 Lubang", satuan: "pcs" },
  { namaBarang: "Paper Clip Kecil", satuan: "box" },
  { namaBarang: "Paper Clip Besar", satuan: "box" },
  { namaBarang: "Binder Clip 19mm", satuan: "box" },
  { namaBarang: "Binder Clip 25mm", satuan: "box" },
  { namaBarang: "Binder Clip 32mm", satuan: "box" },
  { namaBarang: "Binder Clip 41mm", satuan: "box" },
  { namaBarang: "Karet Gelang", satuan: "pack" },
  { namaBarang: "Bantalan Stempel", satuan: "pcs" },
  { namaBarang: "Tinta Stempel", satuan: "botol" },
  { namaBarang: "Cutting Mat A3", satuan: "pcs" },
  { namaBarang: "Tempat Pensil", satuan: "pcs" },
  { namaBarang: "Tray Dokumen Susun 3", satuan: "set" },
  { namaBarang: "Kotak Memo", satuan: "pcs" },
  { namaBarang: "Papan Jalan/Clipboard A4", satuan: "pcs" },
  { namaBarang: "Name Tag/ID Card Holder", satuan: "pcs" },
  { namaBarang: "Tali Lanyard", satuan: "pcs" },
  { namaBarang: "Kalkulator Meja", satuan: "pcs" },
  { namaBarang: "Kalkulator Saku", satuan: "pcs" },
  { namaBarang: "Jam Dinding Kantor", satuan: "pcs" },
  { namaBarang: "Tempat Tisu Meja", satuan: "pcs" },
  { namaBarang: "Alas Meja Mika", satuan: "pcs" },
  { namaBarang: "Sandaran Kaki (Footrest)", satuan: "pcs" },
  { namaBarang: "Kabel Ties", satuan: "pack" },
  { namaBarang: "Kotak Pensil Organizer", satuan: "pcs" },
  { namaBarang: "Papan Nama Meja Akrilik", satuan: "pcs" },
  { namaBarang: "Tempat Kartu Nama", satuan: "pcs" },
  { namaBarang: "Push Pin/Paku Payung", satuan: "box" },
  { namaBarang: "Penjepit Kertas Meja (Letter Tray)", satuan: "pcs" },
  { namaBarang: "Organizer Laci Meja", satuan: "pcs" },

  // Map, Filing, Organizer
  { namaBarang: "Map Snelhecter Plastik", satuan: "pcs" },
  { namaBarang: "Map Kancing", satuan: "pcs" },
  { namaBarang: "Map Ordner Folio", satuan: "pcs" },
  { namaBarang: "Map Ordner A4", satuan: "pcs" },
  { namaBarang: "Box File Folio", satuan: "pcs" },
  { namaBarang: "Box File A4", satuan: "pcs" },
  { namaBarang: "Stopmap Folio", satuan: "pcs" },
  { namaBarang: "Clear Holder/Sleeve A4", satuan: "pcs" },
  { namaBarang: "Ring Binder A4", satuan: "pcs" },
  { namaBarang: "Divider/Sekat Binder", satuan: "set" },
  { namaBarang: "Hanging Folder", satuan: "pcs" },
  { namaBarang: "Expanding File/Map Akordeon", satuan: "pcs" },
  { namaBarang: "Plastik Klip Dokumen", satuan: "pack" },
  { namaBarang: "Label Ordner", satuan: "pack" },
  { namaBarang: "Folder Gantung Arsip", satuan: "pcs" },
  { namaBarang: "Kotak Arsip Kardus", satuan: "pcs" },
  { namaBarang: "Amplop Arsip Besar", satuan: "pcs" },
  { namaBarang: "Map Presentasi/Portofolio", satuan: "pcs" },
  { namaBarang: "Binder Ring 3cm", satuan: "pcs" },
  { namaBarang: "Binder Ring 5cm", satuan: "pcs" },

  // Consumables Printer / Komputer
  { namaBarang: "Tinta Printer Hitam", satuan: "botol" },
  { namaBarang: "Tinta Printer Cyan", satuan: "botol" },
  { namaBarang: "Tinta Printer Magenta", satuan: "botol" },
  { namaBarang: "Tinta Printer Yellow", satuan: "botol" },
  { namaBarang: "Cartridge Tinta Original Hitam", satuan: "pcs" },
  { namaBarang: "Cartridge Tinta Original Warna", satuan: "pcs" },
  { namaBarang: "Toner Printer Laser Hitam", satuan: "pcs" },
  { namaBarang: "Toner Printer Laser Warna", satuan: "pcs" },
  { namaBarang: "Drum Unit Printer", satuan: "pcs" },
  { namaBarang: "Pita Printer Dot Matrix", satuan: "pcs" },
  { namaBarang: "Flashdisk 16GB", satuan: "pcs" },
  { namaBarang: "Flashdisk 32GB", satuan: "pcs" },
  { namaBarang: "Hardisk Eksternal 1TB", satuan: "pcs" },
  { namaBarang: "Mouse Optik Kabel", satuan: "pcs" },
  { namaBarang: "Mouse Wireless", satuan: "pcs" },
  { namaBarang: "Keyboard Kabel", satuan: "pcs" },
  { namaBarang: "Keyboard Wireless", satuan: "pcs" },
  { namaBarang: "Mouse Pad", satuan: "pcs" },
  { namaBarang: "Kabel USB Printer", satuan: "pcs" },
  { namaBarang: "Kabel HDMI", satuan: "pcs" },
  { namaBarang: "Kabel LAN/UTP", satuan: "meter" },
  { namaBarang: "USB Hub", satuan: "pcs" },
  { namaBarang: "Cleaning Kit Layar/Keyboard", satuan: "set" },
  { namaBarang: "CD/DVD Blank", satuan: "pack" },
  { namaBarang: "Card Reader", satuan: "pcs" },

  // Kebersihan & Pantry Kantor
  { namaBarang: "Tisu Wajah Kotak", satuan: "box" },
  { namaBarang: "Tisu Gulung", satuan: "pack" },
  { namaBarang: "Tisu Basah", satuan: "pack" },
  { namaBarang: "Sabun Cuci Tangan Cair", satuan: "botol" },
  { namaBarang: "Hand Sanitizer", satuan: "botol" },
  { namaBarang: "Pengharum Ruangan Semprot", satuan: "botol" },
  { namaBarang: "Pengharum Ruangan Elektrik Isi Ulang", satuan: "pcs" },
  { namaBarang: "Kantong Plastik Sampah Kecil", satuan: "pack" },
  { namaBarang: "Kantong Plastik Sampah Besar", satuan: "pack" },
  { namaBarang: "Kapur Barus", satuan: "pack" },
  { namaBarang: "Pembersih Kaca Semprot", satuan: "botol" },
  { namaBarang: "Pembersih Lantai", satuan: "botol" },
  { namaBarang: "Pembersih Meja/Multipurpose", satuan: "botol" },
  { namaBarang: "Lap Meja Microfiber", satuan: "pcs" },
  { namaBarang: "Lap Pel", satuan: "pcs" },
  { namaBarang: "Sapu Lidi/Ijuk", satuan: "pcs" },
  { namaBarang: "Sikat WC", satuan: "pcs" },
  { namaBarang: "Gelas Plastik Sekali Pakai", satuan: "pack" },
  { namaBarang: "Sendok Plastik Sekali Pakai", satuan: "pack" },
  { namaBarang: "Tusuk Gigi", satuan: "pack" },
  { namaBarang: "Kopi Sachet", satuan: "box" },
  { namaBarang: "Teh Celup", satuan: "box" },
  { namaBarang: "Gula Sachet", satuan: "box" },
  { namaBarang: "Krimer Sachet", satuan: "box" },
  { namaBarang: "Air Mineral Galon", satuan: "galon" },
  { namaBarang: "Air Mineral Botol", satuan: "dus" },

  // Elektronik Kecil & Baterai
  { namaBarang: "Baterai AA", satuan: "pack" },
  { namaBarang: "Baterai AAA", satuan: "pack" },
  { namaBarang: "Baterai 9V", satuan: "pcs" },
  { namaBarang: "Charger Baterai", satuan: "pcs" },
  { namaBarang: "Lampu LED Meja", satuan: "pcs" },
  { namaBarang: "Extension Cable/Colokan Listrik", satuan: "pcs" },
  { namaBarang: "Stop Kontak Portable", satuan: "pcs" },
  { namaBarang: "Kipas Angin Meja Mini", satuan: "pcs" },
  { namaBarang: "Senter LED", satuan: "pcs" },
  { namaBarang: "Adaptor Charger HP", satuan: "pcs" },
  { namaBarang: "Power Bank", satuan: "pcs" },
  { namaBarang: "Earphone/Headset", satuan: "pcs" },
  { namaBarang: "Webcam", satuan: "pcs" },
  { namaBarang: "Speaker Portable", satuan: "pcs" },
  { namaBarang: "Baterai Remote AC/TV", satuan: "pcs" },

  // Perlengkapan Rapat / Presentasi
  { namaBarang: "Whiteboard Marker Set", satuan: "box" },
  { namaBarang: "Penghapus Whiteboard", satuan: "pcs" },
  { namaBarang: "Flip Chart Paper", satuan: "pack" },
  { namaBarang: "Papan Tulis Kecil Portable", satuan: "pcs" },
  { namaBarang: "Laser Pointer", satuan: "pcs" },
  { namaBarang: "Layar Proyektor Portable", satuan: "pcs" },
  { namaBarang: "Name Card Holder Meja Rapat", satuan: "pcs" },
  { namaBarang: "Bantalan/Placemat Meja Rapat", satuan: "pcs" },
  { namaBarang: "Tas Dokumen/Map Presentasi Kulit", satuan: "pcs" },
  { namaBarang: "Buku Tamu", satuan: "pcs" },
  { namaBarang: "Stempel Tanggal Otomatis", satuan: "pcs" },
  { namaBarang: "Stempel Perusahaan Custom", satuan: "pcs" },
  { namaBarang: "Bantal Stempel Ukuran Besar", satuan: "pcs" },
  { namaBarang: "Gembok Kunci Loker", satuan: "pcs" },
];
